### ISSUE TITLE
I am getting below error when i have use the same package file, Can you please help what could be the issue

### ISSUE THREAD

**Issue by karthimathan** [headspinio/appium-lg-webos-driver#27]
acPHQP1WLWRH:appium-lg-webos-driver-boneskull-strongbox karthicks$ npm run test:e2e

 

> appium-lg-webos-driver@0.0.6 test:e2e
> mocha --timeout 40s --slow 10s "./test/e2e/**/*.spec.js"

 

 

  WebOSDriver - E2E
[Appium] Welcome to Appium v2.0.0-beta.56
[Appium] Non-default server args:
[Appium] {
[Appium]   port: 50581
[Appium] }
[Appium] Attempting to load driver webos...
[debug] [Appium] Requiring driver at /Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox
[Appium] Appium REST http interface listener started on 0.0.0.0:50581
[Appium] Available drivers:
[Appium]   - webos@0.0.6 (automationName 'webOS')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
    session with pre-installed app id
2023-06-07T07:07:03.387Z INFO webdriver: Initiate new session using the WebDriver protocol
2023-06-07T07:07:03.401Z INFO webdriver: [POST] http://0.0.0.0:50581/session
2023-06-07T07:07:03.401Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      platformName: 'LGTV',
      'appium:automationName': 'WebOS',
      'appium:deviceName': 'test',
      'appium:deviceHost': '10.12.144.77',
      'appium:appId': 'com.suitest.watchme.app',
      'appium:app': '/Users/karthicks/Lgproject/testpg/webos.ipk',
      'appium:fullReset': true,
      'appium:chromedriverExecutable': undefined,
      'appium:rcMode': 'rc'
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    platformName: 'LGTV',
    'appium:automationName': 'WebOS',
    'appium:deviceName': 'test',
    'appium:deviceHost': '10.12.144.77',
    'appium:appId': 'com.suitest.watchme.app',
    'appium:app': '/Users/karthicks/Lgproject/testpg/webos.ipk',
    'appium:fullReset': true,
    'appium:chromedriverExecutable': undefined,
    'appium:rcMode': 'rc'
  }
}
[HTTP] --> POST /session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"LGTV","appium:automationName":"WebOS","appium:deviceName":"test","appium:deviceHost":"10.12.144.77","appium:appId":"com.suitest.watchme.app","appium:app":"/Users/karthicks/Lgproject/testpg/webos.ipk","appium:fullReset":true,"appium:rcMode":"rc"},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"LGTV","appium:automationName":"WebOS","appium:deviceName":"test","appium:deviceHost":"10.12.144.77","appium:appId":"com.suitest.watchme.app","appium:app":"/Users/karthicks/Lgproject/testpg/webos.ipk","appium:fullReset":true,"appium:rcMode":"rc"}}
[debug] [AppiumDriver@c076] Calling AppiumDriver.createSession() with args: [{"platformName":"LGTV","appium:automationName":"WebOS","appium:deviceName":"test","appium:deviceHost":"10.12.144.77","appium:appId":"com.suitest.watchme.app","appium:app":"/Users/karthicks/Lgproject/testpg/webos.ipk","appium:fullReset":true,"appium:rcMode":"rc"},null,{"alwaysMatch":{"platformName":"LGTV","appium:automationName":"WebOS","appium:deviceName":"test","appium:deviceHost":"10.12.144.77","appium:appId":"com.suitest.watchme.app","appium:app":"/Users/karthicks/Lgproject/testpg/webos.ipk","appium:fullReset":true,"appium:rcMode":"rc"},"firstMatch":[{}]}]
[debug] [AppiumDriver@c076] Event 'newSessionRequested' logged at 1686121623414 (12:37:03 GMT+0530 (India Standard Time))
[Appium] Attempting to find matching driver for automationName 'WebOS' and platformName 'LGTV'
[Appium] The 'webos' driver was installed and matched caps.
[Appium] Will require it at /Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox
[debug] [Appium] Requiring driver at /Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox
[AppiumDriver@c076] Appium v2.0.0-beta.56 creating new WebOSDriver (v0.0.6) session
[AppiumDriver@c076] Checking BaseDriver versions for Appium and WebOSDriver
[AppiumDriver@c076] Appium's BaseDriver version is 9.3.2
[AppiumDriver@c076] WebOSDriver's BaseDriver version is 9.3.2
[debug] [WebOSDriver@bc11] Creating session with W3C capabilities: {
[debug] [WebOSDriver@bc11]   "alwaysMatch": {
[debug] [WebOSDriver@bc11]     "appium:debuggerPort": 9998,
[debug] [WebOSDriver@bc11]     "appium:websocketPort": 3000,
[debug] [WebOSDriver@bc11]     "appium:autoExtendDevMode": true,
[debug] [WebOSDriver@bc11]     "appium:appLaunchCooldown": 3000,
[debug] [WebOSDriver@bc11]     "appium:keyCooldown": 750,
[debug] [WebOSDriver@bc11]     "appium:rcMode": "rc",
[debug] [WebOSDriver@bc11]     "platformName": "LGTV",
[debug] [WebOSDriver@bc11]     "appium:automationName": "WebOS",
[debug] [WebOSDriver@bc11]     "appium:deviceName": "test",
[debug] [WebOSDriver@bc11]     "appium:deviceHost": "10.12.144.77",
[debug] [WebOSDriver@bc11]     "appium:appId": "com.suitest.watchme.app",
[debug] [WebOSDriver@bc11]     "appium:app": "/Users/karthicks/Lgproject/testpg/webos.ipk",
[debug] [WebOSDriver@bc11]     "appium:fullReset": true
[debug] [WebOSDriver@bc11]   },
[debug] [WebOSDriver@bc11]   "firstMatch": [
[debug] [WebOSDriver@bc11]     {}
[debug] [WebOSDriver@bc11]   ]
[debug] [WebOSDriver@bc11] }
[WebOSDriver@bc11 (91618894)] Session created with session id: 91618894-4d34-4a77-a824-3b9b5d996ee4
[WebOSDriver] Extending dev mode on device
[WebOSDriver] Running command: /Users/karthicks/LgWebos/CLI/bin/ares-extend-dev --device test
[WebOSDriver] Getting device info
[WebOSDriver] Running command: /Users/karthicks/LgWebos/CLI/bin/ares-device-info --device test
[WebOSDriver] Uninstalling app 'com.suitest.watchme.app'
[WebOSDriver] Running command: /Users/karthicks/LgWebos/CLI/bin/ares-install -r com.suitest.watchme.app --device test
[WebOSDriver] Installing app 'com.suitest.watchme.app' from /Users/karthicks/Lgproject/testpg/webos.ipk
[WebOSDriver] Running command: /Users/karthicks/LgWebos/CLI/bin/ares-install /Users/karthicks/Lgproject/testpg/webos.ipk --device test
[WebOSDriver] Connecting remote; address any prompts on screen now!
[LGWsClient] Trying to read key from file on disk at /Users/karthicks/Library/Application Support/appium-lg-webos-driver-nodejs/strongbox/clientKey-test.txt
[LGWsClient] Success: key is 'f46f2b28f8d1bef3cd35c18eea38f6c4'
[debug] [LGWsClient] Sending message: {"id":"register_0","type":"register","payload":{"forcePairing":false,"manifest":{"appVersion":"1.1","manifestVersion":1,"permissions":["LAUNCH","LAUNCH_WEBAPP","APP_TO_APP","CLOSE","TEST_OPEN","TEST_PROTECTED","CONTROL_AUDIO","CONTROL_DISPLAY","CONTROL_INPUT_JOYSTICK","CONTROL_INPUT_MEDIA_RECORDING","CONTROL_INPUT_MEDIA_PLAYBACK","CONTROL_INPUT_TV","CONTROL_POWER","READ_APP_STATUS","READ_CURRENT_CHANNEL","READ_INPUT_DEVICE_LIST","READ_NETWORK_STATE","READ_RUNNING_APPS","READ_TV_CHANNEL_LIST","WRITE_NOTIFICATION_TOAST","READ_POWER_STATE","READ_COUNTRY_INFO","READ_SETTINGS","CONTROL_TV_SCREEN","CONTROL_TV_STANBY","CONTROL_FAVORITE_GROUP","CONTROL_USER_INFO","CHECK_BLUETOOTH_DEVICE","CONTROL_BLUETOOTH","CONTROL_TIMER_INFO","STB_INTERNAL_CONNECTION","CONTROL_RECORDING","READ_RECORDING_STATE","WRITE_RECORDING_LIST","READ_RECORDING_LIST","READ_RECORDING_SCHEDULE","WRITE_RECORDING_SCHEDULE","READ_STORAGE_DEVICE_LIST","READ_TV_PROGRAM_INFO","CONTROL_BOX_CHANNEL","READ_TV_ACR_AUTH_TOKEN","READ_TV_CONTENT_STATE","READ_TV_CURRENT_TIME","ADD_LAUNCHER_CHANNEL","SET_CHANNEL_SKIP","RELEASE_CHANNEL_SKIP","CONTROL_CHANNEL_BLOCK","DELETE_SELECT_CHANNEL","CONTROL_CHANNEL_GROUP","SCAN_TV_CHANNELS","CONTROL_TV_POWER","CONTROL_WOL"],"signatures":[{"signature":"eyJhbGdvcml0aG0iOiJSU0EtU0hBMjU2Iiwia2V5SWQiOiJ0ZXN0LXNpZ25pbmctY2VydCIsInNpZ25hdHVyZVZlcnNpb24iOjF9.hrVRgjCwXVvE2OOSpDZ58hR+59aFNwYDyjQgKk3auukd7pcegmE2CzPCa0bJ0ZsRAcKkCTJrWo5iDzNhMBWRyaMOv5zWSrthlf7G128qvIlpMT0YNY+n/FaOHE73uLrS/g7swl3/qH/BGFG2Hu4RlL48eb3lLKqTt2xKHdCs6Cd4RMfJPYnzgvI4BNrFUKsjkcu+WD4OO2A27Pq1n50cMchmcaXadJhGrOqH5YmHdOCj5NSHzJYrsW0HPlpuAx/ECMeIZYDh6RMqaFM2DXzdKX9NmmyqzJ3o/0lkk/N97gfVRLW5hA29yeAwaCViZNCP8iC9aO0q9fQojoa7NQnAtw==","signatureVersion":1}],"signed":{"appId":"com.lge.test","created":"20140509","localizedAppNames":{"":"LG Remote App","ko-KR":"리모컨 앱","zxx-XX":"ЛГ Rэмotэ AПП"},"localizedVendorNames":{"":"LG Electronics"},"permissions":["TEST_SECURE","CONTROL_INPUT_TEXT","CONTROL_MOUSE_AND_KEYBOARD","READ_INSTALLED_APPS","READ_LGE_SDX","READ_NOTIFICATIONS","SEARCH","WRITE_SETTINGS","WRITE_NOTIFICATION_ALERT","CONTROL_POWER","READ_CURRENT_CHANNEL","READ_RUNNING_APPS","READ_UPDATE_INFO","UPDATE_FROM_REMOTE_APP","READ_LGE_TV_INPUT_EVENTS","READ_TV_CURRENT_TIME"],"serial":"2f930e2d2cfe083771f68e4fe7bb07","vendorId":"com.lge"}},"pairingType":"PROMPT","client-key":"f46f2b28f8d1bef3cd35c18eea38f6c4"}}
[debug] [LGWsClient] Got response: {"type":"registered","id":"register_0","payload":{"client-key":"f46f2b28f8d1bef3cd35c18eea38f6c4"}}
[debug] [LGWsClient] Sending message: {"id":"request_1","type":"request","payload":{},"uri":"ssap://com.webos.service.networkinput/getPointerInputSocket"}
[debug] [LGWsClient] Got response: {"type":"response","id":"request_1","payload":{"socketPath":"ws://10.12.144.77:3000/resources/45c92db27160a7717915dcca6f891e4acf1c9d1f/netinput.pointer.sock","returnValue":true}}
[WebOSDriver] Launching app 'com.suitest.watchme.app'
[WebOSDriver] Running command: /Users/karthicks/LgWebos/CLI/bin/ares-launch com.suitest.watchme.app --device test
[WebOSDriver] Waiting for app launch to take effect
[WebOSDriver] Waiting for app launch to take effect
[debug] [Chromedriver@1239] Changed state to 'starting'
[Chromedriver@1239] Set chromedriver binary as: /Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v2.26
[debug] [Chromedriver@1239] Killing any old chromedrivers, running: pkill -15 -f "/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v2.26.*--port=50595"
[Chromedriver@1239] No old chromedrivers seem to exist
[Chromedriver@1239] Spawning chromedriver with: /Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v2.26 --port=50595 --verbose
[debug] [Chromedriver@1239] Chromedriver version: '2.26.436421'
[debug] [Chromedriver@1239] Chromedriver v. 2.26.436421 does not fully support W3C protocol. Defaulting to MJSONWP
[debug] [Chromedriver@1239] Matched '/status' to command name 'getStatus'
[debug] [Chromedriver@1239] Proxying [GET /status] to [GET http://127.0.0.1:50595/status] with no body
[debug] [Chromedriver@1239] Got response with status 200: {"sessionId":"","status":0,"value":{"build":{"version":"alpha"},"os":{"arch":"x86_64","name":"Mac OS X","version":"10.16.0"}}}
[Chromedriver@1239] Starting MJSONWP Chromedriver session with capabilities: {
[Chromedriver@1239]   "desiredCapabilities": {
[Chromedriver@1239]     "chromeOptions": {
[Chromedriver@1239]       "debuggerAddress": "10.12.144.77:9998"
[Chromedriver@1239]     },
[Chromedriver@1239]     "loggingPrefs": {
[Chromedriver@1239]       "browser": "ALL"
[Chromedriver@1239]     }
[Chromedriver@1239]   }
[Chromedriver@1239] }
[debug] [Chromedriver@1239] Matched '/session' to command name 'createSession'
[debug] [Chromedriver@1239] Proxying [POST /session] to [POST http://127.0.0.1:50595/session] with body: {"desiredCapabilities":{"chromeOptions":{"debuggerAddress":"10.12.144.77:9998"},"loggingPrefs":{"browser":"ALL"}}}
[debug] [Chromedriver@1239] Webview version: ''
[debug] [Chromedriver@1239] Got response with status 200: {"sessionId":"01a5771b8763b329a4ba3d1e2af68b0b","status":0,"value":{"acceptSslCerts":true,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"browserName":"chrome","chrome":{"chromedriverVersion":"2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6)"},"cssSelectorsEnabled":true,"databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"javascriptEnabled":true,"locationContextEnabled":true,"mobileEmulationEnabled":false,"nativeEvents":true,"pageLoadStrategy":"normal","platform":"","rotatable":false,"takesHeapSnapshot":true,"takesScreenshot":true,"unexpectedAlertBehaviour":"","version":"","webStorageEnabled":true}}
[Chromedriver@1239] Determined the downstream protocol as 'MJSONWP'
[debug] [Chromedriver@1239 (01a5771b)] Changed state to 'online'
[WebOSDriver] Waiting for app launch to take effect
[WebOSDriver] Clearing app local storage & reloading
[debug] [Chromedriver@1239 (01a5771b)] Matched '/execute/sync' to command name 'execute'
[Chromedriver@1239 (01a5771b)] Rewrote the original URL '/execute/sync' to '/execute' for MJSONWP protocol
[debug] [Chromedriver@1239 (01a5771b)] Proxying [POST /execute] to [POST http://127.0.0.1:50595/session/01a5771b8763b329a4ba3d1e2af68b0b/execute] with body: {"script":"return (() => {\n        window.localStorage.clear();\n        window.location.reload();\n    }).apply(null, arguments)","args":[]}
[debug] [Chromedriver@1239 (01a5771b)] Got response with status 200: {"sessionId":"01a5771b8763b329a4ba3d1e2af68b0b","status":13,"value":{"message":"unknown error: call function result missing 'value'\n  (Session info: content shell=)\n  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.16.0 x86_64)"}}
[debug] [MJSONWP] Matched JSONWP error code 13 to UnknownError
[debug] [AppiumDriver@c076] Event 'newSessionStarted' logged at 1686121635869 (12:37:15 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@c076] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown error: call function result missing 'value'
[debug] [AppiumDriver@c076]   (Session info: content shell=)
[debug] [AppiumDriver@c076]   (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.16.0 x86_64)
[debug] [AppiumDriver@c076]     at errorFromMJSONWPStatusCode (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/@appium/base-driver/lib/protocol/errors.js:1021:10)
[debug] [AppiumDriver@c076]     at ProxyRequestError.getActualError (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/@appium/base-driver/lib/protocol/errors.js:907:14)
[debug] [AppiumDriver@c076]     at JWProxy.command (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:340:19)
[debug] [AppiumDriver@c076]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [AppiumDriver@c076]     at async Chromedriver.sendCommand (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/appium-chromedriver/build/lib/lib/chromedriver.js:630:12)
[debug] [AppiumDriver@c076]     at async WebOSDriver._WebOSDriver_executeChromedriverScript (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/build/lib/driver.js:309:12)
[debug] [AppiumDriver@c076]     at async WebOSDriver.executeChromedriverScript (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/build/lib/driver.js:170:16)
[debug] [AppiumDriver@c076]     at async WebOSDriver.createSession (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/build/lib/driver.js:139:13)
[debug] [AppiumDriver@c076]     at async AppiumDriver.createSession (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/appium/lib/appium.js:349:35)
[HTTP] <-- POST /session 500 12492 ms - 1971
[HTTP] 
2023-06-07T07:07:15.907Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: unknown error: call function result missing 'value'
  (Session info: content shell=)
  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.16.0 x86_64)
2023-06-07T07:07:15.908Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: unknown error: call function result missing 'value'
  (Session info: content shell=)
  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.16.0 x86_64)
    at getErrorFromResponseBody (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/webdriver/build/utils.js:198:12)
    at NodeJSRequest._request (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/webdriver/build/request/index.js:166:60)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startWebDriverSession (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/webdriver/build/utils.js:68:20)
    at async Function.newSession (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/webdriver/build/index.js:46:45)
    at async remote (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/node_modules/webdriverio/build/index.js:77:22)
    at async Context.<anonymous> (/Users/karthicks/lg/appium-lg-webos-driver-boneskull-strongbox/test/e2e/driver.e2e.spec.js:73:16)
      1) "before all" hook for "should start and stop a session via pre-installed app id"
      2) "after all" hook for "should send remote keys"
[HTTP] Waiting until the server is closed
[HTTP] Received server close event

 

  0 passing (13s)
  2 failing

 

  1) WebOSDriver - E2E
       session with pre-installed app id
         "before all" hook for "should start and stop a session via pre-installed app id":
     Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: unknown error: call function result missing 'value'
  (Session info: content shell=)
  (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.16.0 x86_64)
      at startWebDriverSession (node_modules/webdriver/build/utils.js:73:15)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Function.newSession (node_modules/webdriver/build/index.js:46:45)
      at async remote (node_modules/webdriverio/build/index.js:77:22)
      at async Context.<anonymous> (test/e2e/driver.e2e.spec.js:73:16)

 

  2) WebOSDriver - E2E
       session with pre-installed app id
         "after all" hook for "should send remote keys":
     TypeError: Cannot read properties of undefined (reading 'deleteSession')
      at Context.<anonymous> (test/e2e/driver.e2e.spec.js:77:20)
      at processImmediate (node:internal/timers:476:21)

**Comment by jlipps** [comment]
this issue is because the version of chromedriver is too old apparently. you could try to update the clear logic in the driver to return something like `{value: null}` instead of not returning anything and see if that helps?
