### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by josipalos** [headspinio/appium-lg-webos-driver#62]
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: read ECONNRESET
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: read ECONNRESET
    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)
    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)

**Comment by mlopezuno** [comment]
Similar issue:

Connecting remote; address any prompts on screen now!
[debug] [AppiumDriver@94a2] Event 'newSessionStarted' logged at 1727300679590 (15:44:39 GMT-0600 (Central Standard Time))
[debug] [AppiumDriver@94a2] Encountered internal error running command: Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
[HTTP] <-- POST /session 500 4536 ms - 594 
2024-09-25T21:44:39.601Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: read ECONNRESET
2024-09-25T21:44:39.602Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: read ECONNRESET

**Comment by mlopezuno** [comment]
Was able to connect by adding the following to my capabilities:
`'appium:useSecureWebsocket': true,`

**Comment by regan-karlewicz** [comment]
I can confirm I am also seeing this issue intermittently. I've seen this occur on a LG C3 and C1PUB. 

### Versions

- Appium server 2.13.0
- Webdriverio 8.41.0

### Other context

I have `useSecureWebsocket` set to true, and `websocketPortSecure` set to 3001. I also have `NODE_TLS_REJECT_UNAUTHORIZED=0` set in the environment per the advice in the README. 

### Server side logs:

```
{"context":{"requestId":"f215b07f-5657-4161-a8a1-105ada911d75","sessionId":"7688daf6-7a38-43af-85ed-2762dd0d50a9","sessionSignature":"7688daf6"},"level":"debug","message":"[7688daf6][AppiumDriver@c74b] Event 'newSessionStarted' logged at 1738868380691 (18:59:40 GMT+0000 (Coordinated Universal Time))"}
{"context":{"requestId":"f215b07f-5657-4161-a8a1-105ada911d75","sessionId":"7688daf6-7a38-43af-85ed-2762dd0d50a9","sessionSignature":"7688daf6"},"level":"debug","message":"[7688daf6][AppiumDriver@c74b] Encountered internal error running command: Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:216:20)\n    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)"}
{"context":{"requestId":"f215b07f-5657-4161-a8a1-105ada911d75","sessionId":"7688daf6-7a38-43af-85ed-2762dd0d50a9","sessionSignature":"7688daf6"},"level":"info","message":"[7688daf6][HTTP] <-- POST /session 500 15649 ms - 686 "}
```

### Client side logs:

```
2025-02-06T22:22:00.437Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: read ECONNRESET
```

I will report back if I have any more details.
